"""add leads table with enums

Revision ID: 5aa988a72a52
Revises: cd56b655dabf
Create Date: 2026-05-27 01:25:07.964309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa988a72a52'
down_revision: Union[str, Sequence[str], None] = 'cd56b655dabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_full_name', sa.String(length=200), nullable=False),
    sa.Column('contact_type', sa.Enum('parent', 'student', 'other', name='contact_type'), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telegram', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('student_full_name', sa.String(length=200), nullable=True),
    sa.Column('student_age', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.Enum('piano', 'guitar', 'vocals', 'violin', 'drums', 'other', name='discipline'), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='level'), nullable=True),
    sa.Column('lesson_format', sa.Enum('individual', 'group', 'online', name='lesson_format'), nullable=True),
    sa.Column('preferred_branch', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.Enum('website', 'phone', 'social', 'referral', 'advertising', 'other', name='lead_channel'), nullable=False),
    sa.Column('utm_campaign', sa.String(length=200), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'trial_scheduled', 'converted', 'rejected', name='lead_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
