"""add students table with FK to users and leads

Revision ID: 6877c50422a2
Revises: 776d3d187ace
Create Date: 2026-05-30 03:07:05.920876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6877c50422a2'
down_revision: Union[str, Sequence[str], None] = '776d3d187ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    discipline_enum = postgresql.ENUM(
        'piano', 'guitar', 'vocals', 'violin', 'drums', 'other',
        name='discipline',
        create_type=False,
    )
    student_status_enum = postgresql.ENUM(
        'active', 'paused', 'finished', 'dropped',
        name='student_status',
        create_type=False,
    )
    student_status_enum.create(op.get_bind(), checkfirst=True)


    op.create_table('students',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=200), nullable=False),
        sa.Column('discipline', discipline_enum, nullable=False),
        sa.Column('branch', sa.String(length=100), nullable=True),
        sa.Column('enrollment_date', sa.Date(), nullable=False),
        sa.Column('status', student_status_enum, nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=True),
        sa.Column('lead_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    postgresql.ENUM(name='student_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
